

- name: Enabling and restarting systemd service
  systemd:
    name: '{{service_name}}.service'
    state: stopped
    enabled: no
  when: ansible_service_mgr == 'systemd'

- name: Restarting service
  service:
    name: '{{service_name}}'
    enabled: no
    state: stopped
  become: yes
  when: ansible_service_mgr == 'upstart'



